name: Frontend Deploy Main

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Frontend via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/billing-baba-frontend || exit 1
            git reset --hard
            git clean -fd
            git pull origin main
            npm install --force
            npm run build
            pm2 restart billing-baba-frontend || pm2 start billing-baba-frontend
